name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Crear proyecto
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Preparar archivos
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
